spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/controle_orcamento
    username: postgres
    password: postgres
    initialization-mode: always

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL9Dialect
        temp:
          use_jdbc_metadata_defaults: false
    hibernate:
      ddl-auto: create-drop

  jackson:
    serialization.WRITE_DATES_AS_TIMESTAMPS: false

server:
  port: 8080




