spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://ec2-54-163-254-143.compute-1.amazonaws.com:5432/deq6f7804skrik?sslmode=require
    tomcat:
      test-while-idle: true
      validation-query: SELECT 1
      max-active: 5
    username: udpqyywbwqrnsx
    password: 1607f59fef207fbd2b0ea4c3ac567461162cbfd0a2b578c527b74b719c2a0e7c

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.PostgreSQLDialect

  jackson:
    serialization.WRITE_DATES_AS_TIMESTAMPS: false

server:
  port: 8092