INSERT INTO client (name,password,username) values ('luiz henrique', '$2a$10$QhAxvOfeaN1/mSDbpcl6UehmgcccUk5n.3wGW.ZOydz1l0Pq2jIdy','luiz.reis');
INSERT INTO role (name) values ('USER');
INSERT INTO client_roles values (1,1);
INSERT INTO category (description,type,user_id) VALUES ('Carro','OUT',1);
INSERT INTO category (description,type,user_id) VALUES ('Salario','IN',1);
INSERT INTO category (description,type,user_id) VALUES ('Moto','OUT',1);
INSERT INTO account (description,balance,user_id) values ('banco do brasil',12.50,1);
INSERT INTO account (description,balance,user_id) values ('bradesco',12,1);
INSERT INTO expense (description,data,value,category_id,account_id,effetived) values ('oil change','2017-10-14', 32.50,1,1,true);
INSERT INTO income (description,data,value,category_id,account_id,received) values ('salary','2017-10-05',1500.00,2,1,true);
